-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLzhMZi5yOVYPX8ZT
3xq0XVgpJuhyOrZ3nFtgIvLNtrGgCgYIKoZIzj0DAQehRANCAAQCpdORufzwifnY
StIiU7f1p3D40EpS4VDPfVmTfMtjf+xX8HUPipZsqVRlgdu0ArCvPP0o6fOMtNRT
Y7z+UCsy
-----END PRIVATE KEY-----